(use-modules (ice-9 safe-r5rs))
(define (make-scope)
  (let ((m (make-module)))
    (module-define! m 'display display)
    (module-define! m 'newline newline)
    (module-use! m (null-environment 5))
    m))
