# -*- Ruby -*-

def doc_output(doc)
  File.dirname(doc) + '/../html/' + File.basename(doc, ".rst") + ".html"
end

FileList['src/*.rst'].each do |doc|
  output = doc_output(doc)
  file output => doc do
    sh "src/compile-doc.py #{doc} > #{output}"
  end
  task :doc => output
end

desc "Generate HTML document"
task :doc

task :default => :doc
